services:
  backend:
    build: ./game
    container_name: tic_tac_toe_back
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    build: 
      context: ./tic-tac-toe-web
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: tic_tac_toe_front
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=${VITE_API_URL}
    

networks:
  app-network:
    driver: bridge